etl_waterlevel:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres # use your docker-compose service name or 127.0.0.1
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: raw
